// src/constants/action-types.js
const ADD_ALLOY = 'ADD_ALLOY';
const ADD_WAX_WEIGHT = 'ADD_WAX_WEIGHT';
const SELECTED_ALLOY = 'SELECTED_ALLOY';
const CALCULATE_ALLOY = 'CALCULATE_ALLOY';

export {
	ADD_ALLOY,
	ADD_WAX_WEIGHT,
	SELECTED_ALLOY,
	CALCULATE_ALLOY
}
